services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: N8N_EDITION
        value: community
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: false
      - key: N8N_DISABLE_PRODUCTION_MAIN_MENU
        value: true
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: GENERIC_TIMEZONE
        value: Europe/Athens
      - key: TZ
        value: Europe/Athens
      - key: WEBHOOK_URL
        value: https://n8n-7v4o.onrender.com
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
