services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: WEBHOOK_URL
        value: https://n8n-7v4o.onrender.com
      - key: GENERIC_TIMEZONE
        value: Europe/Athens
      - key: TZ
        value: Europe/Athens
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: false
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 5
