services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: WEBHOOK_URL
        value: https://n8n-7v4o.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: nicktouro29062001
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: false
      - key: GENERIC_TIMEZONE
        value: Europe/Athens
      - key: TZ
        value: Europe/Athens
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 5

databases:
  - name: n8n-db
    plan: basic-1gb
